### PR TITLE
Check if thrown object is error in ErrorBoundary

### LINKED ISSUE #532: Handle error events and objects without message property in setError
## Background

We received a [bug report](https://github.com/appsignal/appsignal-javascript/issues/531) about events being reported as errors automatically in the React integration.

## The problem

The [React's ErrorBoundary](https://github.com/appsignal/appsignal-javascript/blob/main/packages/react/src/ErrorBoundary.tsx) we provide, moves every Error passed to `componentDidCatch`, into `setError`. Sometimes, these errors are events such as [`CloseEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent). The [`setError`](https://github.com/appsignal/appsignal-javascript/blob/main/packages/javascript/src/span.ts#L41-L60) function tries to access the `message` property of every error moved. If not accessible/non-existing, it sets a string informing that something that might not be an error has been reported as one. This string message calls `JSON.stringify()` for the non-error instance; this is not a good practice as some properties are missed while parsing, and the object ends up looking like: `"{"isTrusted":true}"`.

## The proposal(s)

- Don't treat events as errors unless their type is `error`.
- If the object is an `Event` and its type is `error`, don't write the information message and use its properties instead.
- Fix the `JSON.stringify()` call to include all the relevant properties.

### PR DESCRIPTION
**Pull request by tombruijn**
In JavaScript an app can throw any object, not just errors. For example:
`throw new Event("my event")`.

Before we track those thrown objects as errors in AppSignal, make sure
the object is actually an error. I've added the `isError` function for
that in the core library to make this reusable in the future. This
function is then used in the React ErrorBoundary.

For the `isError` tests I had to cast the arguments to `is any`, because
otherwise TypeScript would complain about giving an incompatible type.
Something which the ErrorBoundary itself has no issues with
apparently.

Fixes #532

### CODE REVIEW

File: packages/react/src/ErrorBoundary.tsx [hunk 1]
```diff
@@ -13,6 +14,9 @@ export class ErrorBoundary extends React.Component<Props, State> {
   }
 
   public componentDidCatch(error: Error): void {
+    if (!isError(error)) {
+      return
+    }
```
Comment (luismiramirez) [inline packages/react/src/ErrorBoundary.tsx:19]: Does this work?

```suggestion
    if (!isError(error)) return
```

**Review by luismiramirez — APPROVED** [review]

**Comment by tombruijn** [comment]
@luismiramirez can you re-review? I found an issue with `getDerivedStateFromError`. It now also checks if the given object is an error or not. Otherwise it would render the error state, even if we didn't track it.

**Review by luismiramirez — APPROVED** [review]

**Review by unflxw — APPROVED** [review]

**Review by jeffkreeftmeijer — APPROVED** [review]
