### PR TITLE
Fix errors when run in React Native

### LINKED ISSUE #36: React Native integration

### PR DESCRIPTION
**Pull request by xadamy**
Closes #36. 

This allows React Native/Expo users to use the `@appsignal/javascript` package.

Adds a less strict Promise feature detection function, that is less fussy about non-native promises. We already had issues with this with the RSVP.js library. Also removes the necessity to check for `window.origin.location` in a React Native environment.

### CODE REVIEW

File: packages/javascript/src/environment.ts [hunk 1]
```diff
@@ -15,6 +15,12 @@ export class Environment {
    * @return  {string}       The origin URL
    */
   public static origin(): string {
+    // We check for React Native here. React Native and Expo do
+    // not have an origin per se, so we handle that case.
+    if (navigator.product === "ReactNative" && !window.location) {
+      return "No origin available in React Native"
```
Comment (tombruijn) [inline packages/javascript/src/environment.ts]: Can we also return an empty string and log a warning or something else? Otherwise this string may end up somewhere it shouldn't be?

Comment (xadamy) [reply packages/javascript/src/environment.ts]: Fixed!

**Comment by dalezak** [comment]
We're hoping to integrate AppSignal into our React Native app, wondering how others have done this. Were you able to catch errors in the app using this javascript library? How are native errors handled? Any insight or suggestions would be greatly appreciated.
